set(_CATKIN_CURRENT_PACKAGE "quiz4_a2")
set(quiz4_a2_VERSION "0.1.0")
set(quiz4_a2_MAINTAINER "Alen Alempijevic <Alen.Alempijevic@uts.edu.au>")
set(quiz4_a2_PACKAGE_FORMAT "1")
set(quiz4_a2_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(quiz4_a2_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(quiz4_a2_BUILDTOOL_DEPENDS "catkin")
set(quiz4_a2_BUILDTOOL_EXPORT_DEPENDS )
set(quiz4_a2_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(quiz4_a2_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(quiz4_a2_TEST_DEPENDS )
set(quiz4_a2_DOC_DEPENDS )
set(quiz4_a2_URL_WEBSITE "")
set(quiz4_a2_URL_BUGTRACKER "")
set(quiz4_a2_URL_REPOSITORY "")
set(quiz4_a2_DEPRECATED "")